name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn run build
          yarn run lint
          yarn run prettier
          yarn run test

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t $TOKEN -B $REF
        env:
          CI: true
          TOKEN: "${{ secrets.CODECOV_TOKEN }}"
          REF: "${{ github.ref }}"
